export { OpenAIClient, type ConfigOpts } from './openai-client.js';
export type {
  APIConnectionError,
  APIConnectionTimeoutError,
  APIError,
  APIUserAbortError,
  AuthenticationError,
  BadRequestError,
  ChatMessage,
  ChatParams,
  ChatResponse,
  ChatStreamChunk,
  ChatStreamParams,
  ChatStreamResponse,
  CompletionParams,
  CompletionResponse,
  CompletionStreamParams,
  CompletionStreamResponse,
  ConflictError,
  EmbeddingParams,
  EmbeddingResponse,
  InternalServerError,
  NotFoundError,
  OpenAIError,
  PermissionDeniedError,
  RateLimitError,
  UnprocessableEntityError,
} from 'ai-fetch';
export type {
  SpeechParams,
  SpeechResponse,
} from './types.js';
